services:
  - type: web
    name: nxtturn-backend-v3
    env: docker
    plan: free
    rootDir: Loopline  # <-- This is the crucial line we were missing
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString