services:
  - type: web
    name: nxtturn-backend-v2
    env: python
    plan: free
    rootDir: Loopline
    
    # This is the correct, top-level key for installing system packages.
    # It must be at the same indentation level as 'name', 'env', etc.
    system_packages:
      - name: libavif-dev
      
    # The build command is now clean and only builds the application.
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    
    # The standard start command.
    startCommand: "gunicorn config.wsgi:application"
    
    # This correctly links your existing database.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString