services:
  - type: web
    name: nxtturn-backend-v3
    env: docker
    plan: free
    
    # This is the correct key for running migrations with Docker.
    # It runs AFTER the build and BEFORE the new version is live.
    releaseCommand: "python manage.py migrate"
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString