services:
  - type: web
    name: nxtturn-backend-v3 # <-- CHANGED: A new unique name
    env: docker
    plan: free
    
    # This correctly links your existing database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString