services:
  - type: web
    name: nxtturn-backend-v2
    env: docker # <-- CHANGED: We are now using Docker
    plan: free
    
    # This correctly links your existing database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString