# The definitive render.yaml for the NxtTurn project

services:
  - type: web
    name: nxtturn-backend-v2
    env: python
    plan: free
    rootDir: Loopline
    
    # This is the correct, top-level key for installing system packages
    system_packages:
      - name: libavif-dev
      
    # This is the correct build command, without system package installations
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    
    # The standard start command for a Django Gunicorn server
    startCommand: "gunicorn config.wsgi:application"
    
    # This correctly links your existing database to this new service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString