services:
  - type: web
    name: nxtturn-backend-v3
    env: docker
    plan: free
    
    # The start command is now a multi-step script.
    # It first runs migrate, then starts the server.
    # Because this runs in the live container, it has the DATABASE_URL.
    startCommand: "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:10000"
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString