services:
  - type: web
    name: nxtturn-backend-v2  # <-- CHANGED: Give it a new, unique name
    env: python
    plan: free                 # Define the plan type (important for free tier)
    rootDir: Loopline
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    nativeEnvironment:
      system_packages:
        - name: libavif-dev

        