services:
  - type: web
    name: nxtturn-backend-v4 # Use a new name to force a rebuild
    env: docker
    plan: free
    rootDir: Loopline
    dockerfilePath: ./Dockerfile # <-- ADD THIS LINE
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nxtturn-db
          property: connectionString