# C:\Users\Vinay\Project\Loopline\e2e_test_utils\views.py

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db.models import Q

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny

from community.models import Follow, Group, StatusPost, Poll, PollOption, UserProfile

User = get_user_model()


# This is our main view for E2E test setup
class TestSetupAPIView(APIView):
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        if not settings.DEBUG:
            return Response(status=status.HTTP_404_NOT_FOUND)

        action = request.data.get("action")
        data = request.data.get("data", {})

        try:
            with transaction.atomic():
                if action == "create_user":
                    username = data.get("username")
                    password = data.get("password", "password123")
                    email = data.get("email", f"{username}@example.com")
                    user, created = User.objects.get_or_create(
                        username=username, 
                        defaults={'email': email}
                    )
                    if created:
                        user.set_password(password)
                        user.save()
                    
                    if data.get("with_picture", False):
                        dummy_image = SimpleUploadedFile(
                            name='test_avatar.gif',
                            content=b'\x47\x49\x46\x38\x39\x61\x01\x00\x01\x00\x80\x00\x00\xff\xff\xff\x00\x00\x00\x21\xf9\x04\x01\x00\x00\x00\x00\x2c\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02\x44\x01\x00\x3b',
                            content_type='image/gif'
                        )
                        profile, _ = UserProfile.objects.get_or_create(user=user)
                        profile.picture.save('test_avatar.gif', dummy_image, save=True)

                    return Response({"message": f"User '{username}' handled."}, status=status.HTTP_201_CREATED)

                elif action == "create_post":
                    author = get_object_or_404(User, username=data.get("username"))
                    post = StatusPost.objects.create(author=author, content=data.get("content"))
                    return Response({"message": "Post created.", "post_id": post.id}, status=status.HTTP_201_CREATED)

                elif action == "create_post_with_poll":
                    author = get_object_or_404(User, username=data.get("username"))
                    post_content = data.get("poll_question", "Default Poll Question")
                    post = StatusPost.objects.create(author=author, content=post_content)
                    poll = Poll.objects.create(post=post, question=data["poll_question"])
                    for option_text in data["poll_options"]:
                        PollOption.objects.create(poll=poll, text=option_text)
                    return Response({"message": "Post with poll created."}, status=status.HTTP_201_CREATED)

                elif action == "create_follow":
                    follower = get_object_or_404(User, username=data.get("follower"))
                    following = get_object_or_404(User, username=data.get("following"))
                    Follow.objects.get_or_create(follower=follower, following=following)
                    return Response({"message": "Follow relationship created."}, status=status.HTTP_201_CREATED)

                elif action == 'cleanup':
                    # This targets ALL known user prefixes generated by the test suite.
                    test_user_prefixes = ['creator_', 'member_', 'user_', 'auth_test_', 'multitab_', 'pollTester', 'interaction_', 'profileEditor', 'pictureRemover', 'pictureUploader', 'user_with_posts_', 'reactive_', 'main_', 'joiner_', 'viewer_', 'follower_', 'denied_', 'blocked_']
                    
                    user_query = Q()
                    for prefix in test_user_prefixes:
                        user_query |= Q(username__startswith=prefix)
                    user_query |= Q(username__in=['userA', 'userB', 'userC'])
                    
                    _, users_deleted_details = User.objects.filter(user_query).delete()
                    
                    # --- REVERTED AND IMPROVED CLEANUP LOGIC ---
                    # We will delete any group whose name ends with a long number, which is a pattern
                    # all your test groups follow. This is safer than `icontains`.
                    _, groups_deleted_details = Group.objects.filter(name__regex=r'\d{10,}$').delete()

                    return Response({
                        'status': 'success',
                        'message': 'Test data cleanup complete.',
                        'users_deleted': users_deleted_details.get('auth.User', 0),
                        'groups_deleted': groups_deleted_details.get('community.Group', 0),
                    }, status=status.HTTP_200_OK)
            
            return Response({"error": "Invalid action specified."}, status=status.HTTP_400_BAD_REQUEST)

        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)