"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---- 3. LOAD THE .env FILE ----
# Construct the path to the .env file located in the BASE_DIR (Loopline directory)
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)
# ---- END OF LOADING .env ----


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ---- 4. MODIFY HOW SECRET_KEY and DEBUG ARE SET ----
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-default-key-if-not-in-env') # Provide a fallback

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').upper() == 'TRUE' # Reads from .env, defaults to False
# ---- END OF MODIFICATION FOR SECRET_KEY AND DEBUG ----

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # Add this

   # 3rd Party Apps
    'rest_framework', # Add this line
    'rest_framework.authtoken',
    'dj_rest_auth',   
    'allauth',                  # Add this
    'allauth.account',          # Add this
    'allauth.socialaccount',    # Add this (optional but often needed)
    'dj_rest_auth.registration',# Add this for registration views specifically    # Add this
    'corsheaders',
    'django_extensions', 

    # Your Apps
    'community', # Or 'community.apps.CommunityConfig'
]

# Add this line somewhere below INSTALLED_APPS
SITE_ID = 1
# Add this setting to disable email verification for now if desired
ACCOUNT_EMAIL_VERIFICATION = 'none'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ---- 5. MODIFY DATABASES SETTING TO USE .env VARIABLES ----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'community_portal'), # Default to community_portal if not in .env
        'USER': os.getenv('DB_USER'),                     # Must be in .env
        'PASSWORD': os.getenv('DB_PASSWORD'),               # Must be in .env
        'HOST': os.getenv('DB_HOST', 'localhost'),        # Default to localhost
        'PORT': os.getenv('DB_PORT', '5432'),             # Default to 5432
    }
}
# ---- END OF DATABASE MODIFICATION ----


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- ADD MEDIA FILES CONFIGURATION ---
MEDIA_URL = '/media/' # The base URL from which media files will be served
MEDIA_ROOT = BASE_DIR / 'mediafiles' # The absolute filesystem path to the directory where media files will be stored
# Ensure BASE_DIR is defined at the top of your settings.py: 
# from pathlib import Path
# BASE_DIR = Path(__file__).resolve().parent.parent
# --- END MEDIA FILES CONFIGURATION ---

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Django REST Framework settings
# --- Copy this whole block ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ], # <-- Note the comma

    # --- PAGINATION SETTINGS ---
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
    # --- END OF PAGINATION SETTINGS ---

}
# --- End of block to copy ---

# Ensure REST_AUTH is configured correctly (defaults are often okay)
# Example: Tell dj-rest-auth to use TokenAuthentication
# Ensure REST_AUTH is configured correctly
REST_AUTH = {
    'TOKEN_AUTHENTICATOR_CLASS': 'rest_framework.authentication.TokenAuthentication',
    # --- ADD THIS LINE ---
    'REGISTER_SERIALIZER': 'dj_rest_auth.registration.serializers.RegisterSerializer',
    # --- END OF ADDITION ---

    # You might have other keys here too
}


CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173', # Your Vite server URL
    'http://127.0.0.1:5173', # Sometimes needed as well
]