"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/


"""
import dj_database_url

from pathlib import Path
import os 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---- 3. LOAD THE .env FILE ----
# Construct the path to the .env file located in the BASE_DIR (Loopline directory)
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)
# ---- END OF LOADING .env ----

IS_PRODUCTION = os.getenv('RENDER') == 'true'




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ---- DYNAMIC SETTINGS FOR SECRET_KEY AND DEBUG ----
SECRET_KEY = os.getenv('SECRET_KEY')

if IS_PRODUCTION:
    DEBUG = False
else:
    DEBUG = True
    if not SECRET_KEY:
        # Use a dummy key for local development if not in .env
        SECRET_KEY = 'a-dummy-secret-key-for-local-development-only'
# ---- END OF DYNAMIC SETTINGS ----

# Replace the debug version of ALLOWED_HOSTS with this one
if IS_PRODUCTION:
    ALLOWED_HOSTS = [os.getenv('RENDER_HOSTNAME')] 
else:
    ALLOWED_HOSTS = ['192.168.31.35', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # Add this

   # 3rd Party Apps
    'rest_framework', # Add this line
    'rest_framework.authtoken',
    'dj_rest_auth',   
    'allauth',                  # Add this
    'allauth.account',          # Add this
    'allauth.socialaccount',    # Add this (optional but often needed)
    'dj_rest_auth.registration',# Add this for registration views specifically    # Add this
    'corsheaders',
    'django_extensions', 
    'cloudinary_storage', 
    'cloudinary',       

    # Your Apps
    'community', # Or 'community.apps.CommunityConfig'
]

# Add this line somewhere below INSTALLED_APPS
SITE_ID = 1
# Add this setting to disable email verification for now if desired
ACCOUNT_EMAIL_VERIFICATION = 'none'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ---- 5. MODIFY DATABASES SETTING TO USE .env VARIABLES ----
# In settings.py

if IS_PRODUCTION:
    # Use the DATABASE_URL from Render's environment for production
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Your original local database settings for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'community_portal'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
# ---- END OF DATABASE MODIFICATION ----


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==============================================================================
# MEDIA FILES (User Uploads)
# ==============================================================================

if IS_PRODUCTION:
    # Use Cloudinary for media storage in production
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    # Use local filesystem for media storage in development
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'mediafiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Django REST Framework settings
# --- Copy this whole block ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ], # <-- Note the comma

    # --- PAGINATION SETTINGS ---
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
    # --- END OF PAGINATION SETTINGS ---

}
# --- End of block to copy ---

# Ensure REST_AUTH is configured correctly (defaults are often okay)
# Example: Tell dj-rest-auth to use TokenAuthentication
# Ensure REST_AUTH is configured correctly
REST_AUTH = {
    'TOKEN_AUTHENTICATOR_CLASS': 'rest_framework.authentication.TokenAuthentication',
    # --- ADD THIS LINE ---
    'REGISTER_SERIALIZER': 'dj_rest_auth.registration.serializers.RegisterSerializer',
    # --- END OF ADDITION ---
     # --- ADD THIS LINE FOR THE USER AVATAR FIX ---
    'USER_DETAILS_SERIALIZER': 'community.serializers.UserSerializer',

    # You might have other keys here too
}


# ==============================================================================
# CORS (Cross-Origin Resource Sharing) SETTINGS
# ==============================================================================

if IS_PRODUCTION:
    # For production, only allow requests from our live Netlify frontend.
    # We also explicitly trust this origin for secure cookie handling in the future.
    # The NETLIFY_APP_URL is set in the Render Environment Variables.
    CORS_ALLOWED_ORIGINS = [os.getenv('NETLIFY_APP_URL')]
    CORS_TRUSTED_ORIGINS = [os.getenv('NETLIFY_APP_URL')]
else:
    # For local development, allow requests from the Vite dev server.
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://192.168.31.35:5173',
    ]