# Generated by Django 5.2 on 2025-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_userprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
