# Generated by Django 5.2 on 2025-04-07 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_forumcategory_forumpost_comment_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forum_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.forumpost')),
                ('status_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.statuspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('forum_post__isnull', True)), fields=('user', 'status_post'), name='unique_user_status_like'), models.UniqueConstraint(condition=models.Q(('status_post__isnull', True)), fields=('user', 'forum_post'), name='unique_user_forum_like'), models.CheckConstraint(condition=models.Q(models.Q(('status_post__isnull', False), ('forum_post__isnull', True)), models.Q(('status_post__isnull', True), ('forum_post__isnull', False)), _connector='OR'), name='like_has_one_target')],
            },
        ),
    ]
