# Generated by Django 5.2 on 2025-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_statuspost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
