# Generated by Django 5.2 on 2025-04-14 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_like'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='forum_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='community_c_content_289f18_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('group__isnull', True)), models.Q(('category__isnull', True), ('group__isnull', False)), _connector='OR'), name='forumpost_has_one_target'),
        ),
    ]
