# Generated by Django 5.2 on 2025-12-05 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community",
            "0005_remove_experience_is_current_remove_experience_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="icon_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="intermediate",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color_theme",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("red", "Red"),
                            ("teal", "Teal"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_categories",
                        to="community.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("user_profile", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="community.skillcategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("category", "name")},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="user",
        ),
    ]
