# Generated by Django 5.2 on 2025-06-12 17:12

import community.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuspost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='statuspost',
            name='video',
        ),
        migrations.AlterField(
            model_name='statuspost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to=community.models.get_post_media_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.statuspost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
