# Generated by Django 5.2 on 2026-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community",
            "0006_alter_skill_options_skill_created_at_skill_icon_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("connections", "Connections & Followers"),
                    ("self", "Only Me"),
                ],
                default="connections",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("connections", "Connections & Followers"),
                    ("self", "Only Me"),
                ],
                default="connections",
                max_length=12,
            ),
        ),
    ]
