# Generated by Django 5.2 on 2026-02-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_userprofile_email_visibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="connections",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="connections",
                max_length=12,
            ),
        ),
    ]
