# Generated by Django 5.2 on 2025-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like on your Post'), ('comment', 'Comment on your Post'), ('reply', 'Reply to your Comment'), ('mention', 'Mention in a Post/Comment')], max_length=50, null=True),
        ),
    ]
