# Generated by Django 5.2 on 2026-04-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_recommendationimpression"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("happy", "Happy"),
                    ("celebrate", "Celebrate"),
                    ("insightful", "Insightful"),
                    ("brilliant", "Brilliant"),
                ],
                default="like",
                max_length=20,
            ),
        ),
    ]
