# Generated by Django 5.2 on 2026-04-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_like_reaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuspost",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="community.statuspost",
            ),
        ),
    ]
