# Generated by Django 5.2 on 2025-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_update_site_domain'),
    ]

    operations = [
    ]
