# Generated by Django 5.2 on 2025-06-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_update_site_domain'),
        ('community', '0013_create_superuser'),
    ]

    operations = [
    ]
