# Generated by Django 5.2 on 2025-07-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_posts', to='community.group'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='community.group'),
        ),
    ]
