# Generated by Django 5.2 on 2025-07-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_statuspost_group_alter_forumpost_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public - Anyone can view content and join directly'), ('private', 'Private - Only members can view content, requires approval to join')], default='public', help_text='Defines who can view content and how users can join.', max_length=10),
        ),
    ]
