# Generated by Django 5.2 on 2025-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_group_slug_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like on your Post'), ('comment', 'Comment on your Post'), ('reply', 'Reply to your Comment'), ('mention', 'Mention in a Post/Comment'), ('follow', 'New Follower')], max_length=50, null=True),
        ),
    ]
