# Generated by Django 5.2 on 2025-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_groupjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like on your Post'), ('comment', 'Comment on your Post'), ('reply', 'Reply to your Comment'), ('mention', 'Mention in a Post/Comment'), ('follow', 'New Follower'), ('group_join_request', 'Group Join Request')], max_length=50, null=True),
        ),
    ]
