# Generated by Django 5.2 on 2025-08-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='group',
        ),
        migrations.DeleteModel(
            name='ForumCategory',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
    ]
