# Generated by Django 5.2 on 2025-10-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community",
            "0027_userprofile_location_userprofile_resume_education_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="headline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
