# Generated by Django 5.2 on 2025-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0029_alter_group_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location_state",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_work_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_site", "On-Site"),
                    ("hybrid", "Hybrid"),
                    ("remote", "Remote"),
                ],
                help_text="Your current primary work arrangement.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_open_to_relocation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_administrative_area",
            field=models.CharField(
                blank=True,
                help_text="State, Province, Region, or Territory",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
