# Generated by Django 5.2 on 2025-11-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0030_remove_userprofile_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="portfolio_url",
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                            ("portfolio", "Personal Portfolio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=512)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="community.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["link_type"],
                "unique_together": {("profile", "link_type")},
            },
        ),
    ]
